name: Terraform CI

on:
  push:
    branches: [ "main" ]

env:            
  AWS_REGION: ap-southeast-1  

jobs:
  CICD:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
   
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      run: terraform fmt -check
      working-directory: environments/dev
   
    - name: Terraform Init
      run: terraform init
      working-directory: environments/dev

      #Run Terraform Validate
    - name: Terraform Validate
      run: terraform validate
      working-directory: environments/dev

      #Run Terraform Plan
    - name: Terraform Plan
      id: plan
      run: |
        terraform plan -var-file="dev.tfvars" -out=tfplan.binary
        terraform show -json tfplan.binary > tfplan.json
      working-directory: environments/dev

    # Upload the plan file as an artifact for easy download and viewing
    - name: Upload Terraform Plan artifact
      uses: actions/upload-artifact@v4
      with:
        name: terraform-plan
        path: tfplan.json


    # - name: Terraform Apply for Dev
    #   run: terraform apply -var-file="dev.tfvars" -auto-approve
    #   working-directory: environments/dev