name: Terraform CI

on:
  push:
    branches: [ "main" ]

env:            
  AWS_REGION: ap-southeast-1  

jobs:
  CICD:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
   
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Change to Terraform directory
      run: cd environments/dev

    - name: Terraform fmt
      run: terraform fmt -check
   
    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan
   
    - name: Terraform Apply for Dev
      run: terraform apply -var-file="environments/dev/dev.tfvars" -auto-approve

    - name: Terraform Apply for Staging
      run: terraform apply -var-file="environments/staging/staging.tfvars" -auto-approve

    - name: Terraform Apply for Prod
      run: terraform apply -var-file="environments/prod/prod.tfvars" -auto-approve